### PR TITLE
Create zh_cn.lang

### PR DESCRIPTION
**Pull request by RisingInIris2017**
Hello ejektaflex!
With this little translations, there will be more Chinese players enjoying your brilliant mod smoothly.
Would you kindhearted have this merged?
Thanks a lot in advance!

### CODE REVIEW

**Comment by RisingInIris2017** [comment]
Yes, definitely. :)

**Comment by ejektaflex** [comment]
@RisingInIris2017 I've added the new localization keys, if you'd still like to work on a translation!

**Comment by RisingInIris2017** [comment]
Yep, I've found that. Thanks for your work!
I have made new localization file for you :)

**Comment by ejektaflex** [comment]
Looks good. This will be included in the next update. 👍

**Pull request merged**
