### PR TITLE
Add tr_tr.json

### PR DESCRIPTION
**Pull request by alpeerkaraca**

### CODE REVIEW

**Comment by ejektaflex** [comment]
As I wrote in #233, normally I do not accept PRs for translations as per the contribution guidelines because we use CrowdIn for translations. However, I can manually upload this file to CrowdIn with your permission, as long as you accept that this file will be synced back to the project under the same license as the project itself.

**Comment by alpeerkaraca** [comment]
Ough, didn't know you have Crowdin. Wish I knew. No problem you are free to upload it'll make me happy either.

**Comment by ejektaflex** [comment]
I've uploaded it to CrowdIn, you can add further translations for missing strings here:
https://crowdin.com/project/bountiful/tr
Thank you!

**Comment by alpeerkaraca** [comment]
Thanks I was busy for a few days. Will do ASAP!

**Pull request closed without merging**
