### PR TITLE
Create es_es.json

### PR DESCRIPTION
**Pull request by zeedif**

### CODE REVIEW

**Comment by ejektaflex** [comment]
Hi @zeedif ! Under normal conditions, I would direct you to make these changes on CrowdIn as per the contribution guidelines - however, `es_es` does not yet exist (only `es_em`), so I will upload these translations to CrowdIn as `es_es`, unless you would rather make the changes on CrowdIn yourself.

**Comment by zeedif** [comment]
I wasn't aware that the mod had a Crowdin project. If it's possible, I would greatly appreciate it if you could add the es_es translation for me.

**Comment by ejektaflex** [comment]
Will do! :)

**Comment by ejektaflex** [comment]
It looks as though es_es is 100% translated (at least in part by you? 👍 ) on CrowdIn, so I am closing this PR. If there are any changes required, you can do so via the CrowdIn page. Thanks!

**Pull request closed without merging**
